# Generated by Django 5.2.8 on 2026-07-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_movie_rate_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=2, upload_to='movies/'),
            preserve_default=False,
        ),
    ]
