# Generated by Django 5.2.8 on 2026-08-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_movie_image_remove_movie_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='movies/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='text',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
