# Generated by Django 5.2.8 on 2026-08-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_movie_image_movie_is_popular_movie_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movies/'),
        ),
    ]
